### ISSUE TITLE
关于网站实例添加

### ISSUE THREAD

**Issue by token01** [hunterhug/GoSpiderExample#1]
问一下能否爬boss招聘的招聘信息 这样根据不同的招聘信息进行推荐

**Comment by hunterhug** [comment]
请详细说明一下，你的需求十分不明确

**Comment by token01** [comment]
是否可以爬取一下 招聘网站的信息 做一个整合网站展示， 比如  boss招聘   拉钩   内推  猎聘 这样的网站 我们根据关键字  go +北京 +3年   整合到一个自己的网站显示？

**Comment by hunterhug** [comment]
可以的，但是要抓哪些字段，要抓多少页，这些细节都很重要，因为每个网站结构都不一样。

**Comment by token01** [comment]
好  可以的话 我可以晚些时间提供一些细节 。

**Comment by token01** [comment]
网站 地址 如何可以 猎聘网站 拉钩 智联招聘 boss直聘 比较常用的招聘网站

主要字段    名字 头像  联系方式  职位  工作经验  职业类型  

主要抓取 最新二个星期 几页的话 我也不是很清楚 看情况而定。  

这只是我初步看法。

**Comment by hunterhug** [comment]
你已经陷入只差一个程序员的状况，这是很危险的。

**Comment by token01** [comment]
我就是程序员  我只是说了一下我的想法
